FROM ubuntu:22.04 AS base

ENV DEBIAN_FRONTEND noninteractive
ENV COMPOSER_ALLOW_SUPERUSER 1



# Install dependencies
RUN apt update
RUN apt install -y software-properties-common
RUN add-apt-repository -y ppa:ondrej/php
RUN apt update
RUN apt install -y php8.2\
    php8.2-cli\
    php8.2-common\
    php8.2-fpm\
    php8.2-mysql\
    php8.2-zip\
    php8.2-gd\
    php8.2-mbstring\
    php8.2-curl\
    php8.2-xml\
    php8.2-bcmath\
    php8.2-pdo\
    php8.2-intl\
    php8.2-imagick 


# Install php-fpm
RUN apt install -y php8.2-fpm php8.2-cli wget curl

# Install composer
RUN apt install -y curl
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install nodejs
RUN apt install -y ca-certificates gnupg
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
ENV NODE_MAJOR 20
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
RUN apt update
RUN apt install -y nodejs

# Install nginx
RUN apt install -y nginx git


COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY docker/default.conf /etc/nginx/sites-available/default


COPY docker/start.sh /start.sh
# COPY docker/start-dev.sh /start-dev.sh
RUN chmod +x /start.sh
# RUN chmod +x /start-dev.sh


COPY . /var/www/html
WORKDIR /var/www/html

# RUN chown -R www-data:www-data /var/www/html

# RUN composer install  


# change permission  for  /var/www to 0777
# RUN chmod 0755 -R /var/www/html

# RUN php artisan optimize:clear



EXPOSE 80
# RUN npm install -g yarn 
# RUN yarn install

# CMD ["sh", "/start-dev.sh", "&", "yarn", "tailwind"]
CMD ["sh", "/start.sh"]